# Generated by Django 2.2.5 on 2022-09-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollectionAPI', '0002_collection_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
